#!/bin/bash

LOGFILE=/autograder/submission/error.out

export PATH=~/.cabal/bin:~/.ghcup/bin:~/.local/bin:$PATH

ghc --version

echo "======= submitted files =========="
ls /autograder/submission /autograder/submission/* /autograder/submission/*/*


## make a place for the results
mkdir -p /autograder/results

## make a place for the project
mkdir -p /autograder/project
cd project

## copy student's code to this directory 
## TODO: (make sure the right files were submitted)
cp -a /autograder/submission/. .

## cp hw specific test harness here
cp -a /autograder/source/. .



## compile the test harness
## cabal -j1 v1-install 2> $LOGFILE
## ghc -main-is GradeScopeMain -o TestMain --make GradeScopeMain.hs 2> $LOGFILE
stack build 2> $LOGFILE

if [[ $? == 0 ]]; then
    ## run the test cases
	 echo "======= TEST OUTPUT ======="
	 stack test
    if [[ $? != 0 ]]; then
        echo "Memory failure when testing submission. Runaway recursion?" > $LOGFILE
        runghc /autograder/source/ReportError.hs $LOGFILE
    fi

	 ## if the testcases succeed, run hlint on the submission and cat the result
	 echo "====== HLINT OUTPUT ======="
	 hlint src/*.hs
else
    echo "Compilation errors:"
    cat $LOGFILE
    runghc /autograder/source/ReportError.hs $LOGFILE
fi


