#!/bin/bash

echo "========== running autograder =========="
LOGFILE=/autograder/submission/error.out

export PATH=~/.cabal/bin:~/.ghcup/bin:~/.local/bin:$PATH

ghc --version

echo "======= submitted files =========="
ls -R /autograder/submission 

## make a place for the results
mkdir -p /autograder/results

## make a place for the project source files
## the -p flag makes the project directory too
mkdir -p /autograder/project/src

## and go there
cd /autograder/project


## copy student's code to this directory 
## the -a flag preserves the directory structure of the files that were submitted
## TODO: (can we make sure the right files were submitted?)
cp -a /autograder/submission/. . 2>$LOGFILE

## if students submitted raw .hs, move them to the src directory
if compgen -G "*.hs" > /dev/null; then
    echo "=== moving to src directory==="
    mv *.hs src 2>$LOGFILE
fi

## cp hw specific test harness here
cp -a /autograder/source/. .

## compile the project, recording the compilation output in case there is an error
stack build 2> $LOGFILE

if [[ $? == 0 ]]; then
    ## run the test cases
    echo "======= TEST OUTPUT ======="
    stack test
    
    if [[ $? != 0 ]]; then
        echo "Memory failure when testing submission. Runaway recursion?" > $LOGFILE
        cd /autograder/haskelltester
        stack runghc -- ReportError.sh $LOGFILE
    fi

    ## if build is successful, hlint
    echo "====== HLINT OUTPUT ======="
    stack exec -- hlint src/*.hs

else
    echo "Compilation errors:"
    cat $LOGFILE
    cd /autograder/haskelltester
    stack runghc -- ReportError.sh $LOGFILE
fi


